/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpleloginsystem;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import org.sqlite.SQLiteJDBCLoader;
/**
 *
 * @author NamelessKing
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection connection = null;
    public Login() {
        initComponents();
        connection = SqliteConnection.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName_jLabel = new javax.swing.JLabel();
        password_jLabel = new javax.swing.JLabel();
        userName_jTextField = new javax.swing.JTextField();
        login_jButton = new javax.swing.JButton();
        password_jPasswordField1 = new javax.swing.JPasswordField();
        loginIcon_jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userName_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userName_jLabel.setText("Username");

        password_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_jLabel.setText("Password");

        userName_jTextField.setToolTipText("");

        login_jButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        login_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ok-icon.png"))); // NOI18N
        login_jButton.setText("Login");
        login_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_jButtonActionPerformed(evt);
            }
        });

        password_jPasswordField1.setToolTipText("");

        loginIcon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/system-login-icon.png"))); // NOI18N
        loginIcon_jLabel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                loginIcon_jLabelComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(loginIcon_jLabel)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userName_jLabel)
                    .addComponent(password_jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userName_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(password_jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(login_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userName_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userName_jLabel))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(password_jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password_jLabel)))
                        .addGap(32, 32, 32)
                        .addComponent(login_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginIcon_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_jButtonActionPerformed
        // TODO add your handling code here:
        try {
            
           String query = 
                   "SELECT * "
                   + "FROM EmployeeInfo "
                   + "WHERE username = ? AND password = ? ";
           
           PreparedStatement pst = connection.prepareStatement(query);
           pst.setString(1, userName_jTextField.getText());
           pst.setString(2, password_jPasswordField1.getText());
           
           ResultSet res = pst.executeQuery();
           
           int count = 0;
           while (res.next()) {
                count++;
           }
           
           if(count == 1){
               JOptionPane.showMessageDialog(null, "Username and password is correct");
               this.dispose();
               EmployeeInfo empInfo = new EmployeeInfo();
               empInfo.setVisible(true);
           }
           else if(count > 1){
               JOptionPane.showMessageDialog(null, "Dublicate Username and password");
           }
           else
               JOptionPane.showMessageDialog(null, "Username and password is not correct.."
                       + "Try Again");
           
           res.close();
           pst.close();
        } catch (Exception e) {
    
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_login_jButtonActionPerformed

    private void loginIcon_jLabelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_loginIcon_jLabelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_loginIcon_jLabelComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    Login window = new Login();
                    window.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginIcon_jLabel;
    private javax.swing.JButton login_jButton;
    private javax.swing.JLabel password_jLabel;
    private javax.swing.JPasswordField password_jPasswordField1;
    private javax.swing.JLabel userName_jLabel;
    private javax.swing.JTextField userName_jTextField;
    // End of variables declaration//GEN-END:variables
}
